shop-static-site/goods/urls.py
from django.contrib import admin
from django.urls import path

from goods import views

app_name ='goods'

urlpatterns = [
    path('search/', views.CatalogView.as_view(), name='search'),
    path('<slug:category_slug>/', views.CatalogView.as_view(), name='index'),
    path('product/<slug:product_slug>/', views.ProductView.as_view(), name='product'),
]

shop-static-site/main/urls.py
from django.contrib import admin
from django.urls import path

from main import views

app_name ='main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

shop-static-site/shopSite/urls.py
import debug_toolbar
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path

from main import views
from shopSite import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="goods")),
    path("user/", include("users.urls", namespace="users")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop-static-site/users/urls.py
from django.contrib import admin
from django.urls import path

from users import views

app_name ='user'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('registration/', views.UserRegistrationView.as_view(), name='registration'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('users-cart/', views.UserCartView.as_view(), name='users_cart'),
    path('logout/', views.logout, name='logout'),
]

shop-static-site/templates/base.html
{% load static %}
{% load goods_tags%}
{% load carts_tags %}
{% users_carts request as carts%}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>ОДО "СпецМетПоставка"</title>
        <link rel="icon" type="image/x-icon" href="{% static "assets/favicon.ico" %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static "css/styles.css" %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top navbar-shrink" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{%url "main:index"%}">СпецМетПоставка</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Меню
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">

                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="#projects">Услуги</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url "user:users_cart" %} ">Корзина(<div id="goods-in-cart-count" style="display:inline">{% if carts.total_quantity%}{{carts.total_quantity}}{% else %}0{% endif %}</div>)</a></li>
                        {% if not user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url "user:login" %}">Войти</a></li>
                        {% else %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    Мой профиль
                                </a>
                                <ul class="dropdown-menu bg-dark">
                                    <li><a class="dropdown-item  text-white" href="{% url "user:profile" %}">Личный кабинет</a>
                                    </li>
                                    {% if user.is_admin or user.is_staff %}
                                        <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">Админ панель</a></li>
                                    {% endif %}
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item  text-white" href="{% url "user:logout" %}">Выйти</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                    <form class="d-flex" style="padding-right:10px" role="search" action="{% url "goods:search"%}" method="get">
                        <input class="form-control me-2" type="search" name="q" placeholder="поиск" aria-label="Search">
                        <button class="btn btn-primary" type="submit">Поиск</button>
                    </form>
                    <div class="dropdown">
                        <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Каталог
                        </button>
                        <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        {% tag_categories as categories %}
                        {% for category in categories %}
                            <li><a class="dropdown-item text-white" href="{% url "goods:index" category.slug%}">{{ category.name }}</a></li>
                        {% endfor %}
                        </ul>
                    </div>

                </div>
            </div>
        </nav>
        <!-- Masthead-->
        
        {% block main %} 

        {% endblock main %}
    
        {% block footer %} 

        {% endblock footer %}

        <!-- Footer-->
        <footer class="footer bg-black small text-center text-white-50"><div class="container px-4 px-lg-5">Металлопрокат в Минске ©2004-2024.&copy; Все права защищены.</div></footer>
        <!-- Bootstrap core JS-->
        <script src="{% static "js/bootstrap/bootstrap.bundle.min.js" %}"></script>
        <!-- Core theme JS-->
        <script src="{% static "js/jquery/jquery-3.7.0.min.js" %}"></script>
        <script src="{% static "js/jquery-ajax.js" %}"></script>
        <script src="{% static "js/scripts.js" %}"></script>

    </body>
</html>