shop-static-site/carts/urls.py
from django.contrib import admin
from django.urls import path

from carts import views

app_name ='carts'

urlpatterns = [
    path('cart_add/', views.CartAddView.as_view(), name='cart_add'),
    path('cart_change/', views.CartChangeView.as_view(), name='cart_change'),
    path('cart_remove/', views.CartRemoveView.as_view(), name='cart_remove'),
]

shop-static-site/goods/urls.py
from django.contrib import admin
from django.urls import path

from goods import views

app_name ='goods'

urlpatterns = [
    path('search/', views.CatalogView.as_view(), name='search'),
    path('<slug:category_slug>/', views.CatalogView.as_view(), name='index'),
    path('product/<slug:product_slug>/', views.ProductView.as_view(), name='product'),
]

shop-static-site/main/urls.py
from django.contrib import admin
from django.urls import path

from main import views

app_name ='main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

shop-static-site/shopSite/urls.py
import debug_toolbar
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path

from main import views
from shopSite import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="goods")),
    path("user/", include("users.urls", namespace="users")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop-static-site/goods/models.py
from django.db import models
from django.forms import CharField
from django.urls import reverse


# Create your models here.
class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Название")
    slug = models.SlugField(
        max_length=200, unique=True, blank=True, null=True, verbose_name="URL"
    )

    class Meta:
        db_table = "category"
        verbose_name = "Категорию"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Название")
    slug = models.SlugField(
        max_length=200, unique=True, blank=True, null=True, verbose_name="URL"
    )
    price = models.DecimalField(
        default=0.00, max_digits=7, decimal_places=2, verbose_name="Цена"
    )
    image = models.ImageField(
        upload_to="goods_images", blank=True, null=True, verbose_name="Изображение"
    )
    category = models.ForeignKey(
        to=Categories, on_delete=models.CASCADE, verbose_name="Категория"
    )
    description = models.TextField(
        max_length=1000, unique=True, blank=True, null=True, verbose_name="Описание"
    )
    discount = models.DecimalField(
        default=0.00, max_digits=4, decimal_places=2, verbose_name="Скидка в %"
    )

    class Meta:
        db_table = "product"
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"

    def __str__(self):
        return self.name

    def display_id(self):
        return f"{self.id:05}"

    def calc_discount(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)
        return self.price
    
    def get_absolute_url(self):
        return reverse("goods:product", kwargs={"product_slug": self.slug})
    

shop-static-site/goods/views.py
from itertools import product
from django.core.paginator import Paginator
from django.shortcuts import render
from django.views.generic import DetailView, ListView

from goods.models import Categories, Products
from goods.utils import q_search


class CatalogView(ListView):
    model = Products
    template_name = "goods/catalog.html"
    context_object_name = "products"
    paginate_by = 3
    allow_empty = False

    def get_queryset(self):
        category_slug = self.kwargs.get("category_slug")
        on_sale = self.request.GET.get("on_sale", None)
        order_by = self.request.GET.get("order_by", None)
        query = self.request.GET.get("q", None)

        if category_slug == "all":
            goods = super().get_queryset()
        elif query:
            goods = q_search(query)
        else:
            goods = super().get_queryset().filter(category__slug=category_slug)

        if on_sale:
            goods = goods.filter(discount__gt=0)

        if order_by and order_by != "default":
            goods = goods.order_by(order_by)
        return goods

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["slug"] = self.kwargs.get("category_slug")
        return context


# Create your views here.
# from goods.models import Products
# from goods.utils import q_search

# def catalog(request, category_slug=None):

#     page = request.GET.get('page',1)
#     on_sale = request.GET.get('on_sale',None)
#     order_by = request.GET.get('order_by',None)
#     query=request.GET.get('q',None)

#     if category_slug == 'all':
#         goods = Products.objects.all()
#     elif query:
#         goods=q_search(query)
#     else:
#         goods = Products.objects.filter(category__slug=category_slug)

#     if on_sale:
#         goods=goods.filter(discount__gt=0)

#     if order_by and order_by!="default":
#         goods=goods.order_by(order_by)

#     paginator = Paginator(goods, 8)
#     current_page = paginator.page(int(page))
#     slug_url = category_slug

#     context ={
#         'products':current_page,
#         'slug':slug_url
#     }
#     return render(request, 'goods/catalog.html',context=context)


class ProductView(DetailView):
    # model = Products
    template_name = "goods/product.html"
    slug_url_kwarg = "product_slug"
    context_object_name = "product"

    def get_object(self, queryset=...):
        product = Products.objects.get(slug=self.kwargs.get(self.slug_url_kwarg))
        return product


# def product(request, product_slug):
#     product = Products.objects.get(slug=product_slug)

#     context ={
#         'product':product
#     }
#     return render(request, 'goods/product.html',context=context)

shop-static-site/goods/templates/goods/catalog.html
{% extends "base.html" %}
{% load static %}
{% load goods_tags %}
{% block main %}
<section class="py-5 masthead" style="display:inline-table">
     <!-- Форма фильтров -->
  
    <div class="container px-4 px-lg-5 mt-5">
        <div class="dropdown mb-2">
            <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Фильтры
            </button>
    
            <form action="{% if request.GET.q %}{% url "goods:search"%}{% else %}{% url "goods:index" slug%}{% endif %}" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on" {% if request.GET.on_sale == 'on' %} checked {% endif %}>
                    {% if request.GET.q %}
                        <input type="hidden" name="q" value="{{request.GET.q}}">
                    {% endif %}
                    <label class="form-check-label" for="flexCheckDefault">
                        Товары по акции
                    </label>
                </div>
                <p class="text-white mx-3 mt-3">Сортировать:</p>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default" checked>
                    <label class="form-check-label" for="flexRadioDefault1">
                        По умолчанию
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price">
                    <label class="form-check-label" for="flexRadioDefault2">
                        От дешевых к дорогим
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price">
                    <label class="form-check-label" for="flexRadioDefault3">
                        От дорогих к дешевым
                    </label>
                </div>
                <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
            </form>
        </div>
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% comment %} {% tag_products as products %} {% endcomment %}
            {% for product in products %}
            <div class="col mb-5">
                <div class="card h-100">
                {% if  product.discount %}
                    <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                {% endif %}
                    <!-- Product image-->
                {% if product.image %}
                    <img class="card-img-top" style="  height: inherit; object-fit: cover;" src="{{ product.image.url }}" alt="{{product.name}}" />
                {% else %}
                    <img class="card-img-top" style="  height: inherit; object-fit: cover;" src="{% static "assets/img/not_found.png" %}" alt="..." />
                {% endif %}
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{ product.name }}</h5>
                            <!-- Product reviews-->
                            <div class="d-flex justify-content-center small text-warning mb-2">
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                            </div>
                        {% if  product.discount%} 
                            <span class="text-muted text-decoration-line-through">{{product.price}} BYN</span>
                            <span>{{product.calc_discount}} BYN</span>
                        {% else %}
                            <span>{{product.price}} BYN</span>
                        {% endif %}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url "goods:product" product.slug%}">Смотреть</a></div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% comment %} pagination {% endcomment %}
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center" style="background-color: black;
    margin-bottom: 0;">
    <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
      <a class="page-link" href="
    {% if page_obj.has_previous %}
        ?{% param_change page=page_obj.previous_page_number %}
    {% else %}
        #
      {% endif %}" tabindex="-1">Назад</a>
    </li>
    {% for page in page_obj.paginator.page_range %}
        {% if  page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
            <li class="page-item">
                <a class="page-link" href="?{% param_change page=page%}">{{page}}</a>
            </li>
        {% endif %}
    {% endfor %}
    <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
        <a class="page-link" href="
        {% if page_obj.has_next %}
           ?{% param_change page=page_obj.next_page_number %}
        {% else %}
            #
          {% endif %}">Вперед</a>
    </li>
  </ul>
</nav>

</body>
{% endblock main%}
{% block footer%}
<!-- Contact-->
<section class="contact-section bg-black">
    <div class="container px-4 px-lg-5">
       
        <div class="social d-flex justify-content-center">
            <a class="mx-2" href="#!"><i class="fab fa-twitter"></i></a>
            <a class="mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
            <a class="mx-2" href="#!"><i class="fab fa-github"></i></a>
        </div>
    </div>
</section>
{%endblock footer%}

shop-static-site/goods/templates/goods/product.html
{% extends "base.html" %}
{% load static %}
{% block main %}
{% load goods_tags %}

<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            
            <div class="col-md-6">           
            <img class="card-img-top mb-5 mb-md-0" src="{{product.image.url}}" alt="..." />
            </div>
            <div class="col-md-6">
                <div class="small mb-1">ID товара:{{product.display_id}}</div>
                <h1 class="display-5 fw-bolder">{{product.name}}</h1>
                <div class="fs-5 mb-5">
                    {% if  product.discount%} 
                        <span class="text-muted text-decoration-line-through">{{product.price}} BYN</span>
                        <span>{{product.calc_discount}} BYN</span>
                    {% else %}
                        <span>{{product.price}} BYN</span>
                    {% endif %}
                   
                </div>
                <p class="lead">{{product.description}}</p>
                <a class="btn btn-outline-dark flex-shrink-0 add-to-cart" 
                    data-product-id={{product.id}} 
                    href={% url "cart:cart_add"%}>
                    {% csrf_token %} 
                    Добавить в корзину
                </a>       
                
            </div>
        </div>
    </div>
</section>
</div>
<!-- Related items section-->
<section class="py-5 bg-light">
    <div class="container px-4 px-lg-5 mt-5">
        <h2 class="fw-bolder mb-4">Популярные товары</h2>
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% tag_products_sell as products %}
            {% for product in products %}
            <div class="col mb-5">
                <div class="card h-100">
                {% if  product.discount %}
                    <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                {% endif %}
                    <!-- Product image-->
                {% if product.image %}
                    <img class="card-img-top" style="  height: inherit; object-fit: cover;" src="{{ product.image.url }}" alt="{{product.name}}" />
                {% else %}
                    <img class="card-img-top" style="  height: inherit; object-fit: cover;" src="{% static "assets/img/not_found.png" %}" alt="..." />
                {% endif %}
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{ product.name }}</h5>
                            <!-- Product reviews-->
                            <div class="d-flex justify-content-center small text-warning mb-2">
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                            </div>
                        {% if  product.discount%} 
                            <span class="text-muted text-decoration-line-through">{{product.price}} BYN</span>
                            <span>{{product.calc_discount}} BYN</span>
                        {% else %}
                            <span>{{product.price}} BYN</span>
                        {% endif %}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url "goods:product" product.slug%}">Смотреть</a></div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock main%}
{% comment %} {% block footer%}
<!-- Contact-->
<section class="contact-section bg-black">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5">
            <div class="col-md-4 mb-3 mb-md-0">
                <div class="card py-4 h-100">
                    <div class="card-body text-center">
                        <i class="fas fa-map-marked-alt text-primary mb-2"></i>
                        <h4 class="text-uppercase m-0">Адрес</h4>
                        <hr class="my-4 mx-auto" />
                        <div class="small text-black-50">ул. Тимирязева, 67, офис 1726, 17 этаж</div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-3 mb-md-0">
                <div class="card py-4 h-100">
                    <div class="card-body text-center">
                        <i class="fas fa-envelope text-primary mb-2"></i>
                        <h4 class="text-uppercase m-0">Почта</h4>
                        <hr class="my-4 mx-auto" />
                        <div class="small text-black-50"><a href="#!">sale@specmet.by</a></div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-3 mb-md-0">
                <div class="card py-4 h-100">
                    <div class="card-body text-center">
                        <i class="fas fa-mobile-alt text-primary mb-2"></i>
                        <h4 class="text-uppercase m-0">Телефон</h4>
                        <hr class="my-4 mx-auto" />
                        <div class="small text-black-50"> + 375 (17) 396-35-86</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="social d-flex justify-content-center">
            <a class="mx-2" href="#!"><i class="fab fa-twitter"></i></a>
            <a class="mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
            <a class="mx-2" href="#!"><i class="fab fa-github"></i></a>
        </div>
    </div>
</section>
{%endblock footer%} {% endcomment %}